name: "CI_CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v1
        with:
          go-version: "1.16.5"

      - name: "Install dependencies"
        run: |
          go version
          go get -u honnef.co/go/tools/cmd/staticcheck@latest

      - name: "Build"
        run: go build .

      - name: "Static Check"
        run: |
          go vet ./...
          $(go list -f {{.Target}} honnef.co/go/tools/cmd/staticcheck) ./...

      - name: "Test"
        run: cd tests && go test -v
